services:
  api:
    build: .
    container_name: movies_api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/movies_catalog
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: movies_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movies_catalog
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -ppassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data:
